services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://root:root@db:5432/nest_melody_match?schema=public
    develop:
      watch:
        - path: ./src
          action: sync
          target: /usr/src/app/src
          ignore:
            - node_modules

        - path: ./prisma
          action: rebuild

        - path: ./package.json
          action: rebuild
  db:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nest_melody_match
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: