services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      TEST: ${TEST}
    volumes:
      - .:/usr/src/app
